Run plugin verifier in CI
sourcegraph/jetbrains pull request #1458
Opened 2024-05-07 03:43 UTC by dominiccooney

This would have caught the regression in #1432 fixed in #1453

## Test plan

CI

2024-05-07 13:18 UTC, pkukielka approved these changes
LGTM

2024-05-07 14:42 UTC, odisseus approved these changes, later dismissed

2024-05-07 18:02 UTC, odisseus commented
It looks like the plugin verifier tool attempts to download several versions of IntelliJ (which constitute a few GB of data). I have no idea why this step fails in CI, but it might be caused by exceeding some kind of traffic quota.

2024-05-08 10:35 UTC, odisseus requested changes, later dismissed
Looks like you need to fix the formatting.

2024-05-08 12:00 UTC, merged