Migrate vcs package to Kotlin
sourcegraph/jetbrains pull request #154
Opened 2023-12-02 00:14 UTC by mkondratek

2023-12-04 07:45 UTC, Sa1to requested changes

2023-12-04 07:45 UTC, Sa1to commented on src/main/kotlin/com/sourcegraph/vcs/RepoUtil.kt
> +  fun findRepositoryName(project: Project, currentFile: VirtualFile?): String? {
I am getting this error 
```
java.lang.IncompatibleClassChangeError:` Expected static method 'java.lang.String com.sourcegraph.vcs.RepoUtil.findRepositoryName(com.intellij.openapi.project.Project, com.intellij.openapi.vfs.VirtualFile)'
	at com.sourcegraph.cody.agent.CodyAgentCodebase.onFileOpened$lambda$1(CodyAgentCodebase.kt:33)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

This method is called with argument of type `VirtualFile` but accepts `VirtualFile?`

2023-12-04 15:34 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/vcs/RepoUtil.kt
> +  fun findRepositoryName(project: Project, currentFile: VirtualFile?): String? {
pls clean build the plugin

2023-12-04 18:42 UTC, Sa1to commented on src/main/kotlin/com/sourcegraph/vcs/RepoUtil.kt
> +                  })
This can be simplified to 
```
      val codebaseName =
          withServer(
                  project
          ) { server: CodyAgentServer? ->
            server!!.convertGitCloneURLToCodebaseName(CloneURL(cloneURL))
          }
```

2023-12-04 18:42 UTC, Sa1to approved these changes
LGTM

2023-12-05 14:42 UTC, exigow requested changes
Thanks for rewriting in Kotlin! 

To sum up: I've dropped a few comments where we can simplify some code. Please have a look. I didn't comment on everything because I didn't want to spend too much time on it. Please try to apply these comments to the entire code, not just the highlighted parts, as a lot of my comments can be easily repeated.

BTW I'm starting to miss tests. I perfectly understand the concerns about not touching code that works, but it seems to me that we could fill these gaps in our spare time, especially since the whole `vcs` package seems to be very isolated / not connected to the UI. With tests, we wouldn't have concerns about simplifying the code more aggressively (aka fearless development :smile:).

2023-12-05 14:42 UTC, exigow commented on src/main/kotlin/com/sourcegraph/vcs/GitUtil.kt
> +    }
This `getRemote` function can be significantly simplified in Kotlin:

```kotlin
private fun getRemote(repository: Repository, project: Project, remoteName: String): GitRemote? =
    GitRepositoryManager.getInstance(project).getRepositoryForRoot(repository.root)
      ?.remotes
      ?.find { x -> x.name == remoteName }
```

If we are doing Java->Kotlin conversion, let's try to pay attention to whether we can simplify something or use the stdlib (especially collections). Ofc I'm not asking for fully rewriting it to idiomatic Kotlin :smile:, but such obvious things like removal of streams or using elvis expr.

2023-12-05 14:42 UTC, exigow commented on src/main/kotlin/com/sourcegraph/vcs/PerforceUtil.kt
> +  }
We can remove Java optional and streams in few spots.

2023-12-05 14:42 UTC, exigow commented on src/main/kotlin/com/sourcegraph/vcs/RepoUtil.kt
> +            .findFirst()
Here too, similarly - we can remove optionals and streams.

2023-12-06 10:16 UTC, mkondratek commented
> Thanks for rewriting to Kotlin!
> 
> To sum up: I've dropped a few comments where we can simplify some code. Please have a look. I didn't comment on everything because I didn't want to spend too much time on it. Please try to apply these comments to the entire code, not just the highlighted parts, as a lot of my comments can be easily repeated.
> 
> BTW I'm starting to miss tests. I perfectly understand the concerns about not touching code that works, but it seems to me that we could fill these gaps in our spare time, especially since the whole `vcs` package seems to be very isolated / not connected to the UI. With tests, we wouldn't have concerns about simplifying the code more aggressively (aka fearless development 😄).

@exigow thanks for the detailed review. I generally agree with you. Let's postpone the merging of this one.

2024-03-06 15:50 UTC, mkondratek commented
closing as it is inactive for a long time already - we need to start over that migration

2024-03-06 15:50 UTC, closed without merging