Add "Upgrade" option to RLE notifications
sourcegraph/jetbrains pull request #166
Opened 2023-12-06 18:57 UTC by mkondratek

2023-12-06 18:58 UTC, mkondratek commented
## Free account & RateLimitError

<img width="479" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/14b46774-9b1a-429a-ae3b-e887a9d23d72">

2023-12-06 22:13 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/statusbar/CodyStatusBarActionGroup.kt
> +        isGa && autocompleteRLE?.upgradeIsAvailable ?: chatRLE?.upgradeIsAvailable ?: false
We may need to add a dependency on the mentioned flag.

2023-12-06 22:13 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/config/CodyAccountListModel.kt
> +    CodyAutocompleteStatusService.resetApplication(project)
btw the status is more up to date now

2023-12-06 22:14 UTC, mkondratek commented on build.gradle.kts
> +    systemProperty("cody.isGa", "true")
before the next stable we may need to turn it off

2023-12-07 14:11 UTC, danielmarquespt commented
Looks good. Can you change the order of the buttons so that its [Upgrade] [Close]?

2023-12-11 09:57 UTC, Sa1to approved these changes
LGTM

2023-12-11 12:16 UTC, exigow reviewed
> This PR adds systemProperty("cody.isGa", "true") to build.gradle. We may need to set it to false before the next stable release.

AFAIK we have to remember about this flag also for nightly builds, not only stable.

2023-12-11 12:22 UTC, exigow reviewed
![image](https://github.com/sourcegraph/jetbrains/assets/5013708/4a0458c4-01f6-4041-97e9-db6557e7aa75)

I've received same notification during autocompletion two times in short period of time. However, this seems to be minor issue.

2023-12-11 12:29 UTC, exigow requested changes
After clicking on a notification in the notification list, the links are deactivated. Is this correct behavior? For example, in this GIF, I click 'Learn more' after which I would like to click 'Upgrade' but I am unable to.

![image](https://github.com/sourcegraph/jetbrains/assets/5013708/e01c0f07-69a3-4232-90cc-8c08ac636447)

2023-12-11 12:38 UTC, mkondratek commented
@exigow thanks for testing. I fixed the link availability. Now, I just hide the balloon instead of expiring the notification.

You should not be able to get more than one autocomplete RLE notifications from automatically invoked autocompletion. I never experienced that. I guess we can ignore it for now.

2023-12-11 13:03 UTC, exigow approved these changes
Thanks for the quick fix! 

I've played around with it a bit and it now looks fine. 

What I miss the most are notification tests, especially since the notifications seems very isolated from the rest, and such tests could be written based on input and expecting the right HTML content. I assume we don't have time for this now, but I think we can look into it later. Maybe I'll try to write something like this, especially since we want to add notification support in the 'Subscription' panel which will share the same state.

2023-12-11 13:05 UTC, merged