Add subscription tab
sourcegraph/jetbrains pull request #171
Opened 2023-12-07 16:45 UTC by Sa1to

It fixes [PLG: Add "Upgrade to Cody Pro" and "Current Usage" settings buttons#149]
(https://github.com/sourcegraph/jetbrains/issues/149)
We need to merge https://github.com/sourcegraph/cody/pull/2274 first
## Test plan
* Log in as Cody Free user
* Check if subscription tab available
* Check if you see correct tier
* Check if you see `Upgrade` and `Check Usage` buttons that are redirecting to `https://sourcegraph.com/cody/subscription` and `https://sourcegraph.com/cody/manage`
* Log in as Cody Pro user
* Check if subscription tab available
* Check if you see correct tier
* Check if you see only `Check Usage` buttons that are redirecting to `https://sourcegraph.com/cody/subscription` and `https://sourcegraph.com/cody/manage`

https://github.com/sourcegraph/jetbrains/assets/9321940/79ccf53d-0685-4b41-815e-511a0beb5f22

2023-12-07 16:47 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/config/test.form
I guess we can drop this file

2023-12-07 16:49 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +  private val subscriptionPanel: JPanel
This file is already a mess. If there is a chance to add anything in a separate file in the first place we should go for it.

2023-12-11 09:02 UTC, vdavid commented
Behavior-wise, 👍  from me as PLG team member. (I'll let Cody JetBrains teammates check the code.)

2023-12-11 09:38 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +      val codyProFeatureFlag = server.evaluateFeatureFlag(GetFeatureFlag("CodyPro"))
tbd if we should limit to sourcegraph.com instance only

2023-12-11 09:38 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/autocomplete/CodyAutocompleteManager.kt
> +    //    runBlocking {
nit: I guess the comment can be dropped

2023-12-11 15:18 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +        val codyProFeatureFlag = server.evaluateFeatureFlag(GetFeatureFlag("CodyPro"))
we should depend on our flag now `cody-pro-jetbrains`

2023-12-11 16:09 UTC, exigow commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +        val codyProFeatureFlag = server.evaluateFeatureFlag(GetFeatureFlag("CodyPro"))
@mkondratek, can you elaborate and/or suggest a change? Szymon finished early today, so he won't be able to update this till tomorrow. 

Does this boil down to changing from `val codyProFeatureFlag = server.evaluateFeatureFlag(GetFeatureFlag("CodyPro"))` to `val codyProFeatureFlag = server.evaluateFeatureFlag(GetFeatureFlag("cody-pro-jetbrains"))`?

2023-12-11 16:23 UTC, Sa1to commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +        val codyProFeatureFlag = server.evaluateFeatureFlag(GetFeatureFlag("CodyPro"))
So should we rely **only** on our internal feature flag or should we have both (one form agent and our internal)?

2023-12-11 16:28 UTC, exigow requested changes
During tests, my IDE freezes and the last log is: `2023-12-11 18:27:13,812 [  37588]   WARN - #c.s.c.a.CodyAgent - No handler for request with method featureFlags/getFeatureFlag`

2023-12-11 16:34 UTC, Sa1to commented
@exigow I have to rebase on master, it requires latest changes in agent 😅

2023-12-12 09:32 UTC, exigow approved these changes
Thanks for the fixes! :+1: 

Issue seems to be fixed with latest bump, but there is still an problem with the short IDE freezing (for less than a second but it's visible). Apparently, we have some code that happens in the AWT thread and it blocks the entire UI. 

We can ignore this problem for now.

2023-12-12 09:32 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +            java.lang.Boolean.getBoolean("cody.isGa")) {
As we decided during the meetings. Let's drop `cody.isGa` condition here. We will request ff exceptions for ones that want to test these features.

2023-12-12 09:40 UTC, mkondratek commented on src/main/java/com/sourcegraph/cody/SubscriptionPanel.kt
> +    row { label("Please refresh IDE after upgrading to Cody Pro") }
pls use the copy from: https://github.com/sourcegraph/jetbrains/issues/178

2023-12-12 09:42 UTC, mkondratek requested changes
pls apply the two fixes I mentioned. 

There is one more nice to have - but we can deliver it later:
We could show the sub tab depending on the account type when it changes. For now when I change to the account that is eligible to see sub tab the tab does not appear. I assume you can add some logic there:
https://sourcegraph.com/github.com/sourcegraph/jetbrains/-/blob/src/main/kotlin/com/sourcegraph/cody/config/CodyPersistentAccountsHost.kt?L29%3A1-30%3A1

2023-12-12 09:47 UTC, mkondratek commented
I created this: https://github.com/sourcegraph/jetbrains/issues/180

2023-12-12 09:50 UTC, mkondratek approved these changes
<img width="508" alt="image" src="https://github.com/sourcegraph/jetbrains/assets/19799111/8edee9a6-f4b0-4a52-9067-70c4ed85affc">


this is good 🚀

2023-12-12 09:53 UTC, merged