Update codyCommit
sourcegraph/jetbrains pull request #285
Opened 2024-01-10 20:18 UTC by mkondratek

2024-01-10 20:24 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/agent/ExtensionConfiguration.kt
> +        mapOf("cody.useContext" to "embeddings", "cody.experimental.symfContext" to false),
@olafurpg , does it make sense?

2024-01-10 20:24 UTC, olafurpg commented on src/main/kotlin/com/sourcegraph/cody/agent/ExtensionConfiguration.kt
> +        mapOf("cody.useContext" to "embeddings", "cody.experimental.symfContext" to false),
This looks right 👍🏻

2024-01-10 20:25 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +    refreshRecipes()
moved from above - probably no actual impact but looks better at the end. I will provide some cleanup to this class in a separate PR

2024-01-10 20:26 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +    tryRestartingAgentIfNotRunning(project)
I tried `:runIde` a few times - with a rate-limited account I saw the issue with commands not loading - this line seems to be a fix

2024-01-11 10:08 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/CodyToolWindowContent.kt
> +      }
unrel fix

2024-01-11 11:46 UTC, mkondratek commented on src/main/kotlin/com/sourcegraph/cody/agent/ExtensionConfiguration.kt
> +        mapOf("cody.useContext" to "embeddings", "cody.experimental.symfContext" to false),
we decided to just cherry pick the telemetry fix - these adjustments are redundant

2024-01-11 12:47 UTC, pkukielka approved these changes
LGTM, but ideally I would like it to target release branch which would be copy of current main state.

2024-01-11 12:48 UTC, exigow requested changes
Chat input seems to be infinitely locked on "Connecting to agent" on private repositories. On public repos like sourcegraph/jetbrains/cody/etc this problem doesn't exists (chat connects to the agent and after a moment the text input becomes usable).

![Selection_033](https://github.com/sourcegraph/jetbrains/assets/5013708/e7963e29-16e1-4f9e-82ec-4366d27c8c37)

I've double-checked this and it appears that the current main branch doesn't have this issue, so the regression must have been introduced with this PR (which seems very strange since the changes are cherry-picked and are solely related to telemetry).

Does anyone have similar experience?

EDIT/NOTE: Sometimes it's working if we launch a private repo first. The problem is fully reproducible if we open another private repo within the same "session".

2024-01-11 16:23 UTC, exigow approved these changes
Works great. The last fix nailed it. :+1:

2024-01-11 16:25 UTC, Sa1to approved these changes

2024-01-12 10:02 UTC, merged