Add more intelligent agent rebuilding
sourcegraph/jetbrains pull request #65
Opened 2023-10-25 13:27 UTC by olafurpg

Previously, we didn't rebuild the agent if the binaries were available on disk. This was problematic because it meant that we don't automatically rebuild the binaries when bumping up the Cody commit. This PR fixes the problem by generating a new `cody-revision.txt` file alongside the agent binaries. This revision file includes the cody commit hash, and we automatically rebuild the binaries if this commit hash doesn't match the cody commit hash in the build.

## Test plan

- `:runIde`, confirm the agent is rebuild
- `:runIde` again, confirm the agent is cached
- Update `codyCommit` hash to a new commit hash
- `:runIde` again, confirm the agent is rebuilt

2023-10-26 10:19 UTC, pkukielka commented on build.gradle.kts
> +    val revisionHasChanged = revision == codyCommit
If `revision == codyCommit` doesn't that mean revision has *not* changed?

2023-10-26 14:45 UTC, exigow requested changes

2023-10-26 14:45 UTC, exigow commented on build.gradle.kts
> +    }
If we replace list with set, sorting will be unnecessary.

2023-11-23 12:07 UTC, olafurpg commented
Closing this. Feel free to pick it up you want this feature

2023-11-23 12:07 UTC, closed without merging